CIF spanish starting with 'U' bug resolved
django/django-localflavor pull request #469
Opened 2022-04-21 05:17 UTC by sandeepN06

**Please replace these instructions with a description of your change. The
'New Fields Only' section should be removed if your pull request
doesn't add any new fields.**

Thanks for your contribution!

Issue : (https://github.com/django/django-localflavor/issues/464)

A checklist is included below which helps us keep the code contributions
consistent and helps speed up the review process. You can add additional
commits to your pull request if you haven't met all of these points on your
first version.

**All Changes**

- [ ] Add an entry to the docs/changelog.rst describing the change.

- [ ] Add an entry for your name in the docs/authors.rst file if it's not
      already there.

**New Fields Only**

- [ ] Prefix the country code to all fields.

- [ ] Field names should be easily understood by developers from the target
      localflavor country. This means that English translations are usually
      not the best name unless it's for something standard like postal code,
      tax / VAT ID etc.

- [ ] Prefer '<country code>PostalCodeField' for postal codes as it's
      international English; ZipCode is a term specific to the United
      States postal system.

- [ ] Add meaningful tests. 100% test coverage is not required but all
      validation edge cases should be covered.

- [ ] Add `.. versionadded:: <next-version>` comment markers to new
      localflavors.

- [ ] Add documentation for all fields.

2022-05-04 21:01 UTC, benkonrath requested changes
Do you have a reference for this change? For instance, an official website that states the CIF types? I'm just wondering why this was missed in the first implementation. Did something change?

This PR itself needs a couple of additional things:
* a test with a CIF number that has a U (if possible)
* a changelog entry

Thanks.

2022-05-05 18:37 UTC, sandeepN06 commented
@benkonrath  This is the reference for the change : https://es.wikipedia.org/wiki/C%C3%B3digo_de_identificaci%C3%B3n_fiscal

2022-05-06 07:50 UTC, benkonrath commented
Ok, thanks!

2022-05-06 07:50 UTC, benkonrath approved these changes

2022-05-06 07:50 UTC, merged